### ISSUE TITLE
get rid of as many dependencies as possible (convert to imports)

### ISSUE THREAD

**Issue by dpastoor** [ronkeizer/vpc#2]
See comment here on using [Imports instead of depends](http://stackoverflow.com/questions/8637993/better-explanation-of-when-to-use-imports-depends)

tl;dr package plays nicer and reduces chance of namespace conflicts (especially dplyr/plyr)

check [dplyr description and source code](https://github.com/hadley/dplyr/blob/master/DESCRIPTION) or ggplot as an example of how can handle functions from other packages, etc. Key is using `::` in front of all function calls.

So internally we'll want to convert df %>% summarize(...) to df %>% dplyr::summarize

**Comment by billdenney** [comment]
This seems to be complete, and I think it can be closed.
