### ISSUE TITLE
Labels in facet_grid

### ISSUE THREAD

**Issue by guiastrennec** [ronkeizer/vpc#29]
Great work on the package !

I wanted to generate nice labels for presentation in a VPC using two stratifying variables. To do so I changed the factors of the stratifying variables in the `sim` and `obs` datasets. However it seems that the `vpc()` function automatically appends the variable name to its value eg. `VAR=1` and uses character strings rather than factor which messes up the order of the panels.

ggplot2 v.2.1.0 now integrates `label_both` function which also allows to append the stratifying variable to its value. I would thus recommend to use the labeller function of ggplot rather than manually creating labels.

**Comment by ronkeizer** [comment]
thanks for letting me know, I'll have a look at the label_both functionality a.s.a.p. Agree it's not optimal a.t.m.

**Comment by ronkeizer** [comment]
you can now use the ggplot labeler functionality. See in-package help
