### ISSUE TITLE
Package installation failure with non-English locale.

### ISSUE THREAD

**Issue by sibojan** [ronkeizer/vpc#31]
In Windows 7 English version,  if the current language for non-Unicode program is set to be other than English, the package won't install successfully.   It keeps saying error and displays random characters like this http://www.pinyinjoe.com/images/faq-sina-uc-installer.jpg.   Consequently, it has to be "English" in the Win7 - Control Panel -Region and Language-administrative- change system locale.  However, other R packages do not see this kind of error with the  non-English locale.

**Comment by ronkeizer** [comment]
hi sibojan, sorry I have little experience with non-English locale. However, there is nothing I specifically do in the code to keep it to English-only, so I'm not sure what is causing this behavior. Let me know if you have a suggestion how to fix it in the code.

**Comment by sibojan** [comment]
Hi Ron,

Thank you for your feedback. I don't know how to fix that at this time
point.  My workaround is that changing the windows locale back to
non-English once I have installed the package successfully. So far, I
haven't seen this problem happened to other R packages. For you records, I
will send you the problem screenshot through email. Maybe it can be fixed
when we get more input.

**Comment by sibojan** [comment]
I tried it again and found this issue has been solved. I think the new version of devtools got it straightened out. So, no problem with  install_github("ronkeizer/vpc") anymore. 
Thank you,

**Comment by ronkeizer** [comment]
thanks for letting me know :)






On Sat, Aug 27, 2016 at 7:00 PM -0700, "Sibo Jiang" <notifications@github.com> wrote:












I tried it again and found this issue has been solved. I think the new version of devtools got it straightened out. So, no problem with  install_github("ronkeizer/vpc") anymore. 

Thank you,
