### ISSUE TITLE
Vpc plots doesn't start from time zero.

### ISSUE THREAD

**Issue by sibojan** [ronkeizer/vpc#39]
The lines and shaded area always start from some points after the time zero, leaving the very front part blank. Not sure that this is due to the vpc nature or something else. 
The following vpc zooms in the first 5 hours of the theophylline case in the online tutorial. 
![clipboard_20170520](https://cloud.githubusercontent.com/assets/11802171/26279278/4d8cb4fa-3d7d-11e7-8aaf-5e4a1fb17db0.jpg)
Thank you,

**Comment by ronkeizer** [comment]
Yes, this is supposed to look like that: the lines / areas connect the weighted midpoints of the bins over the x-axis. If you prefer to have the "blocky" version of the vpc where all bins are shown more explicitly you should specify the "smooth=TRUE" option.

________________________________

**Comment by sibojan** [comment]
Where should I put that  "smooth=TRUE"  option? I tried to put it under either show=list()  or vpc_theme=() but no success. Thanks.

**Comment by ronkeizer** [comment]
it's an argument to the main `vpc()` function. I realize now this specific
argument is not included yet in the documentation at vpc.ronkeizer.com. It
is however explained in the help files, type `?vpc` to get more info on all
arguments.

**Comment by sibojan** [comment]
I set the "smooth=FLASE' and now it would start from time zero. However, the noncontinuous bins apparently look not as pretty as the smooth one. I guess manual specification of smaller bin would make it smoother. Thanks.
![clipboard_20170521](https://cloud.githubusercontent.com/assets/11802171/26284326/3d26430e-3e06-11e7-8490-b02cdfe0fb20.jpg)
