### ISSUE TITLE
move to object oriented system

### ISSUE THREAD

**Issue by dpastoor** [ronkeizer/vpc#4]
Given the long term objective is to make this (somewhat) software agnostic, switching to an object oriented system will probably reduce a lot of headache rather than massive ifelse chains. It will require some reorg but is definitely feasible. The two options I see are the S4 system or the R6 system

S4 pros/cons
- older therefore more documentation
- system used for xpose so can look at source code for ideas (for better or worse)

R6 classes
- newer, faster
- easier to update objects
- in development by winston chang/Rstudio folks
- newer (subject to api changes)

I think either one would be completely sufficient for our means (performance bottlenecks due to object creation, etc will not be an issue), but personally take the opportunities to 'look forward' whenever possible.

Todos:
- [ ] choose OO system
- [ ] determine general 'spec' of how want to handle design (eg separation of data preprocessing, processing, plotting, etc)

**Comment by billdenney** [comment]
This appears to be mostly complete since `vpc()` is S3 generic, I think.  It can probably be closed.
