### ISSUE TITLE
export quantile_cens ?

### ISSUE THREAD

**Issue by smouksassi** [ronkeizer/vpc#49]
Hi Ron quantile_cens is super useful would you please export it ?

**Comment by ronkeizer** [comment]
sure, will do

**Comment by smouksassi** [comment]
Thanks I am  working with @olivierbarriere  on https://github.com/smouksassi/ComputePI we want to bring in customized LLOQ by strata , customized binning by strata , bootstrapping the observed data to have CI on observed and so on. once it is exported we will avoid redefining it and import it from vpc !

**Comment by ronkeizer** [comment]
Sure. The function is now exported in the "dev" branch of the vpc package.
I do have a few more things I want to update before I'll merge this branch
into master and release to CRAN.

**Comment by smouksassi** [comment]
Thanks Ron can you please also allow to pass the ... 
so we can request the type of quantile we want ?
e.g. try to mimick what PSN / Phoenix and or other tools do with their quantiles descriptions.
In the ComputePI repo we are trying to support LLOQ column so you have study specific LLOQ and also different binning within strata. We are also relying on data.table for quicker computations.

**Comment by ronkeizer** [comment]
Sure, can you put in a PR for what you had in mind?

**Comment by smouksassi** [comment]
sure my colleagues just submitted one thank you !
