### ISSUE TITLE
stratification

### ISSUE THREAD

**Issue by yanxiaoyu2001** [ronkeizer/vpc#52]
Hello,

I got the following error message when trying to stratify VPC by two variables. It was written 
as stratify = c("GROUP","CMT"), 

Error in cbind(labels = list(), list(`{`, if (!is.null(.rows) || !is.null(.cols)) { : 
  number of rows of matrices must match (see arg 2)
Could you help to provide some comments.

Thanks,
Xiaoyu

**Comment by ronkeizer** [comment]
hi Xiayu,
thanks for reporting. There was indeed a bug, induced by the labeller. I pushed up a fix which I'll merge into the `master` branch later today.
