### ISSUE TITLE
Show only median in plot

### ISSUE THREAD

**Issue by FannyGallais** [ronkeizer/vpc#53]
Hello,

I am using the vpc function and I was wondering if it is possible to plot only the median of observed and simulated data, without showing the 5% and 95% quantiles? I tried using the "show" option but it does not seem to change anything.

Thank you
Fanny

**Comment by ronkeizer** [comment]
Sorry for late reply, but I think this is what you are looking for:
```
vpc(sim = simple_data$sim, obs = simple_data$obs,
    show = list(obs_dv = FALSE, obs_ci = FALSE, pi = FALSE, pi_as_area = FALSE, pi_ci = FALSE, 
                obs_median = TRUE, 
                sim_median = TRUE, sim_median_ci = TRUE))

```
