### ISSUE TITLE
Last bin for observed data

### ISSUE THREAD

**Issue by friedax7** [ronkeizer/vpc#55]
Hi and thanks for this very nice package.

I was wondering about the behaviour of the lines for the observed data after the last bin which come together at a point for all vpcs I have done with this package.

![_vpc_all_final_Tox_2cmt](https://user-images.githubusercontent.com/49393272/55711979-289d5980-59ee-11e9-92e0-f3ecaa2bcd8a.png)

I've seen it is because the db$aggr_obs dataset in the plot_vpc code contains a bin with minimum and maximum values and bin number set to NA and the bin mid equal to the upper limit of the last "regular" bin. It contains one observation that is above the upper limit of the last bin. Is this intended? Is there a way to turn this off?

Best Regards,

Anna Friedel

**Comment by ronkeizer** [comment]
hi Anna, is there any way you can share a reproducible example that shows this behavior? It does indeed sound like something is not working well with binning here, but it's hard to see from the description if this is a bug or a "feature" :)

**Comment by friedax7** [comment]
Hi Ron,

thanks much for the quick reply. Here's attached some code based on the simple_data included in the package that should explain what happens.

[test_vpc_package.txt](https://github.com/ronkeizer/vpc/files/3058065/test_vpc_package.txt)

Best Regards,

Anna

**Comment by ronkeizer** [comment]
Thanks for the reproducible example, I just pushed a fix to the `master` branch. If you re-install from GitHub, the issue should be gone.
