### ISSUE TITLE
Default percentiles of observations

### ISSUE THREAD

**Issue by Sibojang9** [ronkeizer/vpc#59]
Hi Ron,

I cannot find the documentation for the default percentiles of plotted lines for observed data. Is it (0.05, 0.95)  or (0.025, 0.0975)?  Is there any way that we can specify the percentiles?

Thank you,

Sibo

**Comment by roninsightrx** [comment]
Default for the `pi` is `c(0.05, 0.95)`. You can modify using e.g. `pi = c(0.025, 0.0975)`. `pi` stands for prediction interval.
