### ISSUE TITLE
allow to add a second CI level for "VPC with uncertainty"

### ISSUE THREAD

**Issue by ronkeizer** [ronkeizer/vpc#7]
Based upon a second simulation table in which simulation was done with uncertainty in params. 

Not that important actually, I don't find the VPC with uncertainty very useful as you can't actually use it as a diagnostic check. But should be fairly straightforward to implement once the parsing of the simulation data is extracted away into a separate function.

**Comment by roninsightrx** [comment]
Closing for now until someone requests. This could be a confusing feature IMO.
