### ISSUE TITLE
object 'magrittr_pipe' not found

### ISSUE THREAD

**Issue by Kokomole** [ronkeizer/vpc#71]
Hello Ron,

I tried the basic command of _"vpc"_ package but an error occured: 
```
> library(vpc)
> vpc(sim = simple_data$sim, obs = simple_data$obs)
Error in sim %>% dplyr::group_by(strat, sim, bin) %>% dplyr::summarise(q5 = quantile(dv,  : 
  object 'magrittr_pipe' not found
```
I loaded packages that include the magrittr pipe (dplyr, tidyr, magrittr, tidyverse) but the error still appeared. The magrittr pipe operator can be used in other objects except `vpc()` function.

Could you please find out the reason? 

Thank you.

**Comment by roninsightrx** [comment]
a fix for this is on the way. If you use the latest version in the master branch it should work. A new version will likely be available on CRAN later this week. Thx for reporting.
