### ISSUE TITLE
Error in split_chain when using vpc

### ISSUE THREAD

**Issue by jbwoillard** [ronkeizer/vpc#74]
Dear Ron, I have a new issue when using the vpc function
`Error in split_chain(match.call(), env = env)` 
I google it and saw that it could derive from a magrittr update but even with the update of it I still have the issue.
Do you have any idea on how to fix it?
Many thanks
jb

**Comment by roninsightrx** [comment]
hi JB,
did you try with the latest version of vpc (not CRAN)? Is it still there?
```
devtools::install_github(“ronkeizer/vpc”)
```

best,
Ron

**Comment by jbwoillard** [comment]
Dear Ron, thanks that works well now using the latest version.
All the best
jb
