### ISSUE TITLE
Clarification of pred_corr and loq

### ISSUE THREAD

**Issue by billdenney** [ronkeizer/vpc#77]
Related to #5 

I'm trying to standardize the way that `uloq`, `lloq`, and `pred_corr` are checked, but some of the logic doesn't make sense to me.

Here, it says that pred_corr cannot work with `lloq` or `uloq`:

https://github.com/ronkeizer/vpc/blob/3c04880f9f118f21c7d54d7207452ba6a5661e70/R/vpc.R#L191

But within `format_vpc_input_data()`, it seems to do the opposite, using the LOQs only if `pred_corr` is `TRUE`:

https://github.com/ronkeizer/vpc/blob/3c04880f9f118f21c7d54d7207452ba6a5661e70/R/format_vpc_input_data.R#L29-L35

Am I missing something?

**Comment by roninsightrx** [comment]
It seems to me the if-statement should be `!pred_corr`?
